# Generated by Django 4.2.1 on 2023-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('bootcamp_descripton', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('frontend', 'Front-end Development'), ('backend', 'Back-end Development'), ('full_stack', 'Full-stack Development'), ('UI', 'UI/UX'), ('artificial', 'Artificial Intelligence'), ('security', 'Cyber Security')], default='Front-end Development', max_length=2000)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='images/bootstrap.png', upload_to='images/')),
            ],
        ),
    ]
