# Generated by Django 4.2.2 on 2023-06-18 14:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bootcamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("bootcamp_descripton", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Front-end Development"),
                            ("frontend", "Back-end Development"),
                            ("full_stack", "Full-stack Development"),
                            ("UI", "UI/UX"),
                            ("artificial", "Artificial Intelligence"),
                            ("security", "Cyber Security"),
                        ],
                        default="Front-end Development",
                        max_length=2000,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 7, 18, 14, 5, 2, 435290, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="images/bootstrap.png", upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(default="issue", max_length=500)),
                ("descripton", models.TextField(blank=True)),
            ],
        ),
    ]
