# Generated by Django 4.2.1 on 2023-06-14 21:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 21, 19, 2, 234942, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
