# Generated by Django 4.2.2 on 2023-06-16 17:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0002_bootcamp_end_date_bootcamp_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="category",
            field=models.CharField(
                choices=[
                    ("frontend", "Front-end Development"),
                    ("frontend", "Back-end Development"),
                    ("full_stack", "Full-stack Development"),
                    ("UI", "UI/UX"),
                    ("artificial", "Artificial Intelligence"),
                    ("security", "Cyber Security"),
                ],
                default="Front-end Development",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="bootcamp",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 16, 17, 23, 1, 363006, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(default="Issue", max_length=500)),
                ("descripton", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 6, 16, 17, 23, 1, 363873, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
