# Generated by Django 4.2.2 on 2023-06-16 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bootcamp_end_date_bootcamp_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='category',
            field=models.CharField(choices=[('frontend', 'Front-end Development'), ('frontend', 'Back-end Development'), ('full_stack', 'Full-stack Development'), ('UI', 'UI/UX'), ('artificial', 'Artificial Intelligence'), ('security', 'Cyber Security')], default='Front-end Development', max_length=2000),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 6, 55, 10, 843635, tzinfo=datetime.timezone.utc)),
        ),
    ]
