# Generated by Django 4.2.2 on 2023-06-16 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bootcamp_category_alter_bootcamp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 6, 55, 34, 860416, tzinfo=datetime.timezone.utc)),
        ),
    ]
