# Generated by Django 4.2.2 on 2023-06-16 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_bootcamp_category_alter_bootcamp_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 16, 17, 42, 6, 975547, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 16, 17, 42, 6, 976422, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
