# Generated by Django 4.2.2 on 2023-06-18 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_bootcamp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 7, 32, 19, 612168, tzinfo=datetime.timezone.utc)),
        ),
    ]
