# Generated by Django 4.2.2 on 2023-06-17 08:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0011_alter_bootcamp_end_date_alter_contactus_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 17, 8, 33, 29, 857216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
