# Generated by Django 4.2.2 on 2023-06-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0012_alter_bootcamp_end_date_alter_contactus_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="contactus", name="user",),
        migrations.AlterField(
            model_name="bootcamp",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 17, 8, 34, 33, 483121, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
