# Generated by Django 4.2.1 on 2023-06-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bootcamp_end_date_event_attendance'),
        ('main_app', '0013_remove_contactus_user_alter_bootcamp_end_date'),
    ]

    operations = [
    ]
