# Generated by Django 4.2.2 on 2023-06-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20230618_0849'),
        ('main_app', '0014_merge_20230618_1215'),
    ]

    operations = [
    ]
