# Generated by Django 4.2.1 on 2023-06-19 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_question_contactus_user_alter_bootcamp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 19, 7, 50, 31, 397595, tzinfo=datetime.timezone.utc)),
        ),
    ]
