# Generated by Django 4.2.1 on 2023-06-19 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_bootcamp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 19, 18, 25, 4, 780653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='images/default_avatar.png', upload_to='images/'),
        ),
    ]
