# Generated by Django 4.2.2 on 2023-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bootcamp_end_date'),
        ('main_app', '0018_alter_bootcamp_end_date_alter_event_event_image'),
    ]

    operations = [
    ]
