# Generated by Django 4.2.1 on 2023-06-20 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0019_merge_20230619_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='category',
            field=models.CharField(choices=[('frontend', 'Front-end Development'), ('backend', 'Back-end Development'), ('full_stack', 'Full-stack Development'), ('UI', 'UI/UX'), ('artificial', 'Artificial Intelligence'), ('security', 'Cyber Security')], default='Front-end Development', max_length=2000),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 0, 5, 56, 927917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bootcamp')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
