# Generated by Django 4.2.2 on 2023-06-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_merge_20230619_1946'),
        ('main_app', '0020_alter_bootcamp_category_alter_bootcamp_end_date_and_more'),
    ]

    operations = [
    ]
