# Generated by Django 4.2.2 on 2023-06-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_bootcamp_end_date'),
        ('main_app', '0021_merge_20230620_0517'),
    ]

    operations = [
    ]
