# Generated by Django 4.2.1 on 2023-06-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_merge_20230619_1952'),
        ('main_app', '0021_merge_20230620_0925'),
    ]

    operations = [
    ]
