# Generated by Django 4.2.1 on 2023-06-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_merge_20230620_0702'),
        ('main_app', '0022_merge_20230620_1354'),
        ('main_app', '0023_remove_notification_bootcamp_and_more'),
    ]

    operations = [
    ]
