# Generated by Django 4.2.1 on 2023-06-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_merge_20230620_1607'),
        ('main_app', '0024_merge_20230620_2015'),
    ]

    operations = [
    ]
