# Generated by Django 4.2.2 on 2023-06-21 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_merge_20230621_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 5, 38, 50, 590182, tzinfo=datetime.timezone.utc)),
        ),
    ]
