# Generated by Django 4.2.1 on 2023-06-21 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_merge_20230621_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 7, 37, 8, 994770, tzinfo=datetime.timezone.utc)),
        ),
    ]
