# Generated by Django 4.2.1 on 2023-06-19 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=2048)),
                ('project_description', models.TextField()),
                ('project_date', models.DateField(default=django.utils.timezone.now)),
                ('type_project', models.CharField(choices=[('unit', 'Unit Project'), ('capstone', 'Capstone Project')], default='Unit Project', max_length=2000)),
                ('project_logo', models.ImageField(default='images/default_avatar.png', upload_to='images/')),
                ('github_link', models.URLField(blank=True)),
                ('powerpoint_file', models.FileField(blank=True, upload_to='documents/')),
                ('project_document', models.FileField(blank=True, upload_to='documents/')),
                ('proflie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
