# Generated by Django 4.2.1 on 2023-06-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_proflie_project_profile_alter_profile_avatar'),
    ]

    operations = [
    ]
